spring:
   datasource:
      url: jdbc:mysql://${DB_HOST:localhost}/financas?createDatabaseIfNotExist=true&serverTimezone=UTC
   jpa:
      hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl      
   mvc:
      pathmatch:
            matching-strategy: ant_path_matcher

cloud:
   aws: 
      region: 
         static: 
         auto: false
      stack:
         auto: false
   s3:
      bucket:
         name: financas
         folder: comprovantes
      region:
         name: us-east-1

logging:
  file:
     name: /logs/financas.log
  level:
     root: info