spring:
   datasource:
      url: jdbc:mysql://localhost/financas?createDatabaseIfNotExist=true&serverTimezone=UTC
      username: 
      password: 
   jpa:
      hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl      
      show-sql: true
   security:
      oauth2.resourceserver.jwt.public-key-location: classpath:keys/
   mvc:
      pathmatch:
            matching-strategy: ant_path_matcher

cloud:
   aws: 
      region: 
         static: us-east-1
         auto: false
      stack:
         auto: false
      credentials:
         acess-key: 
         secret-key: 
   s3:
      credentials:
         acess-key: 
         secret-key: 
      bucket:
         name: financas
         folder: comprovantes
      region:
         name: us-east-1

financas:
   security:
      jwt:
         keystore:
            jks-location: classpath:keys/
            password: 
            keypair-alias: 

logging:
  file:
    name: /logs/financas.log
  level:
    root: info