spring:
   datasource:
      url: jdbc:mysql://localhost/financas?createDatabaseIfNotExist=true&serverTimezone=UTC
      username: 
      password: 
   jpa:
      hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl      
      show-sql: false
   security:
      oauth2.resourceserver.jwt.public-key-location: classpath:keys/
   mvc:
      pathmatch:
            matching-strategy: ant_path_matcher

cloud:
   aws:
      region:
         static: 
         auto:
      stack:
         auto:
      credentials:
         acess-key: 
         secret-key: 

financas:
   security:
      jwt:
         keystore:
            jks-location: classpath:keys/
            password: 
            keypair-alias: 