spring:
   datasource:
      url: jdbc:mysql://localhost/financas?createDatabaseIfNotExist=true&serverTimezone=UTC
      username: 
      password: 
   jpa:
      hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl      
      show-sql: false

cloud:
   aws:
      region:
         static: 
         auto: 
      stack:
         auto: 
      credentials:
         acess-key: 
         secret-key: 