spring:
   datasource:
      url: jdbc:mysql://localhost/financas?createDatabaseIfNotExist=true&serverTimezone=UTC
      username: 
      password: 
   jpa:
      hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true